name: horoscope
channels:
  - huggingface
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python
  - pytorch=1.6
  - pytorch-lightning=1.0
  - scikit-learn
  - scipy
  - tabulate
  - tokenizers=0.9
  - tqdm
  - transformers=4.0
  - wandb
  - matplotlib
  - editdistance
  - sacremoses
  - pandas
  - jupyter
  - jupyterlab
  - scrapy